# @TODO: Cache node dependencies
# @TODO: Make sure bundler cache really works
# @TODO: Fetch only UPDATED Contentful articles, not ALL of them
# @TODO: Rebuild only UPDATED pages, not ALL of them
# @TODO: Don't run specs on webhook hit (somehow)

language: ruby
rvm: 2.4.0

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - branch: staging
      env:
        AWS_BUCKET=${AWS_BUCKET_DEV}
        AWS_KEY=${AWS_KEY_DEV}
        AWS_REGION=${AWS_REGION_DEV}
        AWS_SECRET=${AWS_SECRET_DEV}
        CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN_DEV}
        CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID_DEV}
        URL=${URL_DEV}

before_script:
  - nvm install 6
  - npm install -g yarn
  - yarn install
  - 'if [ ${TRAVIS_BRANCH} != "master" ]; then
        DATA_DIR=sample bundle exec rspec spec;
    fi'

script:
  - 'if [ ${TRAVIS_BRANCH} = "master" ] || [ ${TRAVIS_BRANCH} = "staging" ]; then
        bundle exec middleman contentful;
        bundle exec middleman build;
        bundle exec middleman s3_sync;
    fi'
