language: ruby
cache: bundler
rvm: 2.4.0

env:
  - DATA_DIR=sample

before_install: nvm install node
install:
  - bundle install
  - yarn

before_script: bundle exec rspec spec
script:
  - bundle exec middleman contentful
